# https://www.youtube.com/watch?v=ThpnqYpvnIM
# https://github.com/truthseekers/php-docker-simple/blob/master/README.md

version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      #MYSQL_ROOT_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:8080
    

volumes:
  mysql-data: